#!/usr/bin/env python3

"""Get the public key of the authorization server."""

import argparse
import os

parser = argparse.ArgumentParser(description='Get the public key of the authorization server.')

parser.add_argument(
    '-p',
    '--pub-key-path',
    type=str,
    help='Path to the directory where the public key of the auth server is stored.',
    required=True
)
parser.add_argument(
    '-sp',
    '--store-path',
    type=str,
    help='Path to the directory where the public key of the auth server will be stored.',
    required=True
)

args = parser.parse_args()

def get_auth_server_pub_key():
    """Get the public key of the authorization server."""
    os.system(f'cp {args.pub_key_path} {args.store_path}')

get_auth_server_pub_key()
